import { useState, useCallback } from 'react';
import { doc, getDoc, setDoc } from 'firebase/firestore';
import { db } from '../lib/firebase';

export interface QuizQuestionData {
    question: string;
    options: [string, string, string, string];
    correctAnswerIndex: number;
    explanation: string;
}

interface UseQuizEngineReturn {
    questions: QuizQuestionData[];
    loading: boolean;
    error: string | null;
    fetchQuiz: () => Promise<void>;
}

const FALLBACK_QUESTIONS: QuizQuestionData[] = [
    {
        question: 'Did you thoroughly understand this module?',
        options: ['Yes, completely', 'Mostly', 'Not really', 'No'],
        correctAnswerIndex: 0,
        explanation: 'Great! Confidence in your understanding is key to moving forward.',
    },
];

export const useQuizEngine = (nodeId: string, topicName: string): UseQuizEngineReturn => {
    const [questions, setQuestions] = useState<QuizQuestionData[]>([]);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const fetchQuiz = useCallback(async () => {
        if (!nodeId || !topicName) return;

        setLoading(true);
        setError(null);

        try {
            // Step 1: Cache Check — look for existing quiz in Firestore
            const quizDocRef = doc(db, 'quizzes', nodeId);
            const quizSnapshot = await getDoc(quizDocRef);

            if (quizSnapshot.exists()) {
                const cachedData = quizSnapshot.data();
                if (cachedData?.questions && Array.isArray(cachedData.questions) && cachedData.questions.length > 0) {
                    setQuestions(cachedData.questions as QuizQuestionData[]);
                    setLoading(false);
                    return;
                }
            }

            // Step 2: API Generation — call Gemini
            const API_KEY = import.meta.env.VITE_GEMINI_API_KEY;
            if (!API_KEY) {
                throw new Error('Gemini API Key is missing.');
            }

            const prompt = `Generate a 5-question multiple-choice quiz about '${topicName}'. Return ONLY raw JSON without markdown formatting. Schema: [ { "question": string, "options": [string, string, string, string], "correctAnswerIndex": number, "explanation": string } ]`;

            const response = await fetch(
                `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${API_KEY}`,
                {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        contents: [{ parts: [{ text: prompt }] }],
                    }),
                }
            );

            const data = await response.json();

            if (data.error) {
                console.error('Gemini API Error:', data.error);
                throw new Error(data.error.message || 'Gemini API error');
            }

            const rawText = data.candidates?.[0]?.content?.parts?.[0]?.text;
            if (!rawText) {
                throw new Error('No content generated by Gemini.');
            }

            // Clean markdown fences if present
            const cleanedText = rawText.replace(/```json/g, '').replace(/```/g, '').trim();
            const parsedData: QuizQuestionData[] = JSON.parse(cleanedText);

            if (!Array.isArray(parsedData) || parsedData.length === 0) {
                throw new Error('Invalid quiz data structure from Gemini.');
            }

            // Step 3: Cache Save — persist to Firestore
            await setDoc(quizDocRef, { questions: parsedData });

            setQuestions(parsedData);
        } catch (err: any) {
            console.error('Quiz Engine Error:', err);
            setError(err.message || 'Failed to generate quiz.');

            // Fallback so user is never blocked
            setQuestions(FALLBACK_QUESTIONS);
        } finally {
            setLoading(false);
        }
    }, [nodeId, topicName]);

    return { questions, loading, error, fetchQuiz };
};
