import React, { useState } from 'react';
import { X, Send, ChevronDown, Bug, Lightbulb, HelpCircle, Mail, Github, Loader, CheckCircle } from 'lucide-react';
import { collection, addDoc, serverTimestamp } from 'firebase/firestore';
import { db } from '../lib/firebase';
import { useStore } from '../store/useStore';
import clsx from 'clsx';

interface HelpSupportModalProps {
    isOpen: boolean;
    onClose: () => void;
}

const CATEGORIES = [
    { key: 'bug' as const, label: 'Bug', icon: Bug, color: 'red' },
    { key: 'feature' as const, label: 'Feature', icon: Lightbulb, color: 'amber' },
    { key: 'question' as const, label: 'Question', icon: HelpCircle, color: 'blue' },
];

const PLACEHOLDERS: Record<string, string> = {
    bug: "Describe the bug — what happened vs. what you expected...",
    feature: "What feature would improve your learning experience?",
    question: "What would you like to know?",
};

const FAQ_ITEMS = [
    {
        q: "How do AI-generated roadmaps work?",
        a: "When you search for a topic we don't have, our AI (Gemini) creates a structured learning path with modules tailored to your query. These are cached so the community benefits too."
    },
    {
        q: "How is my progress tracked?",
        a: "Each module you complete is saved to your profile in real-time. Your progress syncs across devices as long as you're logged in."
    },
    {
        q: "What does the quiz do?",
        a: "The quiz tests your understanding of a module before marking it complete. You need to score 80% or higher to pass. Questions are generated by AI based on the module content."
    },
    {
        q: "Is my data private?",
        a: "Yes. Your progress, profile, and feedback are stored securely in Firebase and are only accessible to you. We don't share or sell any user data."
    },
    {
        q: "Can I use MentorMap offline?",
        a: "MentorMap is a PWA, so previously visited pages may load offline. However, generating new roadmaps, quizzes, and fetching resources requires an internet connection."
    },
];

const APP_VERSION = '1.0.0';

const HelpSupportModal: React.FC<HelpSupportModalProps> = ({ isOpen, onClose }) => {
    const { currentUser } = useStore();

    const [category, setCategory] = useState<'bug' | 'feature' | 'question'>('bug');
    const [message, setMessage] = useState('');
    const [submitting, setSubmitting] = useState(false);
    const [submitted, setSubmitted] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [openFaq, setOpenFaq] = useState<number | null>(null);

    if (!isOpen) return null;

    const handleSubmitFeedback = async () => {
        if (!message.trim() || submitting || !currentUser) return;

        setSubmitting(true);
        setError(null);

        try {
            await addDoc(collection(db, 'feedback'), {
                userId: currentUser.uid,
                email: currentUser.email,
                category,
                message: message.trim(),
                createdAt: serverTimestamp(),
                appVersion: APP_VERSION,
            });
            setSubmitted(true);
            setMessage('');
            setTimeout(() => setSubmitted(false), 3000);
        } catch (_err) {
            setError('Failed to submit feedback. Please try again.');
        } finally {
            setSubmitting(false);
        }
    };

    const toggleFaq = (index: number) => {
        setOpenFaq(openFaq === index ? null : index);
    };

    return (
        <div className="fixed inset-0 z-[60] flex items-end sm:items-center justify-center bg-black/80 backdrop-blur-sm"
            onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}
        >
            <div className={clsx(
                "w-full sm:max-w-md bg-background rounded-t-2xl sm:rounded-2xl border border-slate-200 dark:border-slate-700/50 shadow-2xl shadow-slate-200/50 dark:shadow-none",
                "animate-in slide-in-from-bottom duration-300 max-h-[85vh] overflow-y-auto"
            )}>
                {/* Header */}
                <div className="sticky top-0 bg-background/90 backdrop-blur-md flex items-center justify-between px-5 py-4 border-b border-slate-200 dark:border-slate-700/50 z-10">
                    <h2 className="text-lg font-bold text-foreground">Help & Support</h2>
                    <button onClick={onClose} className="p-1.5 rounded-full hover:bg-muted transition-colors text-muted-foreground">
                        <X size={20} />
                    </button>
                </div>

                <div className="p-5 space-y-6">

                    {/* ── Section 1: Feedback Form ── */}
                    <section>
                        <h3 className="text-xs uppercase tracking-wider text-slate-500 dark:text-slate-400 font-medium mb-3">Send Feedback</h3>

                        {/* Category Picker */}
                        <div className="flex gap-2 mb-3">
                            {CATEGORIES.map(({ key, label, icon: Icon, color }) => (
                                <button
                                    key={key}
                                    onClick={() => setCategory(key)}
                                    className={clsx(
                                        "flex-1 flex items-center justify-center gap-1.5 py-2 rounded-lg text-xs font-medium transition-all duration-200 active:scale-95",
                                        category === key
                                            ? `bg-${color}-500/15 text-${color}-400 border border-${color}-500/30`
                                            : "bg-slate-50 dark:bg-slate-800 text-slate-500 dark:text-slate-400 border border-slate-200 dark:border-slate-700/50 hover:bg-slate-100 dark:hover:bg-slate-700/80"
                                    )}
                                >
                                    <Icon size={14} />
                                    {label}
                                </button>
                            ))}
                        </div>

                        {/* Message */}
                        <textarea
                            value={message}
                            onChange={(e) => setMessage(e.target.value)}
                            placeholder={PLACEHOLDERS[category]}
                            rows={4}
                            maxLength={1000}
                            className="w-full px-4 py-3 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700/50 text-slate-900 dark:text-foreground text-sm placeholder:text-slate-400 dark:placeholder:text-slate-500 focus:outline-none focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500/20 transition-colors resize-none"
                        />
                        <div className="flex items-center justify-between mt-1">
                            <span className="text-[10px] text-slate-500">{message.length}/1000</span>
                        </div>

                        {/* Error */}
                        {error && (
                            <div className="bg-red-500/10 border border-red-500/20 text-red-500 text-sm rounded-xl px-4 py-2 mt-2">
                                {error}
                            </div>
                        )}

                        {/* Submit */}
                        <button
                            onClick={handleSubmitFeedback}
                            disabled={submitting || !message.trim() || submitted}
                            className={clsx(
                                "w-full h-11 mt-3 rounded-xl flex items-center justify-center gap-2 text-sm font-semibold transition-all duration-200 active:scale-[0.98]",
                                submitted
                                    ? "bg-emerald-500 text-white"
                                    : submitting || !message.trim()
                                        ? "bg-muted text-slate-400 dark:text-slate-500 cursor-not-allowed"
                                        : "bg-emerald-600 text-white hover:bg-emerald-500 shadow-lg shadow-emerald-500/20"
                            )}
                        >
                            {submitting ? (
                                <Loader size={16} className="animate-spin" />
                            ) : submitted ? (
                                <CheckCircle size={16} />
                            ) : (
                                <Send size={16} />
                            )}
                            {submitting ? 'Sending...' : submitted ? 'Thanks for your feedback!' : 'Submit Feedback'}
                        </button>
                    </section>

                    {/* ── Section 2: FAQ Accordion ── */}
                    <section>
                        <h3 className="text-xs uppercase tracking-wider text-slate-500 dark:text-slate-400 font-medium mb-3">Frequently Asked Questions</h3>
                        <div className="space-y-1">
                            {FAQ_ITEMS.map((item, i) => (
                                <div key={i} className="rounded-xl border border-slate-200 dark:border-slate-700/50 overflow-hidden">
                                    <button
                                        onClick={() => toggleFaq(i)}
                                        className="w-full flex items-center justify-between px-4 py-3 text-left text-sm font-medium text-foreground hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors"
                                    >
                                        <span>{item.q}</span>
                                        <ChevronDown
                                            size={16}
                                            className={clsx(
                                                "text-slate-500 dark:text-slate-400 shrink-0 ml-2 transition-transform duration-200",
                                                openFaq === i && "rotate-180"
                                            )}
                                        />
                                    </button>
                                    {openFaq === i && (
                                        <div className="px-4 pb-3 text-sm text-slate-600 dark:text-slate-400 leading-relaxed border-t border-slate-200 dark:border-slate-700/30">
                                            <p className="pt-2">{item.a}</p>
                                        </div>
                                    )}
                                </div>
                            ))}
                        </div>
                    </section>

                    {/* ── Section 3: Contact & Socials ── */}
                    <section>
                        <h3 className="text-xs uppercase tracking-wider text-slate-500 dark:text-slate-400 font-medium mb-3">Get in Touch</h3>
                        <div className="space-y-2">
                            <a
                                href="mailto:serveshkrr@gmail.com"
                                className="flex items-center gap-3 px-4 py-3 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700/50 hover:bg-slate-100 dark:hover:bg-slate-700/80 hover:border-slate-300 dark:hover:border-slate-600 transition-all text-foreground text-sm"
                            >
                                <Mail size={18} className="text-slate-500 dark:text-slate-400" />
                                <span>serveshkrr@gmail.com</span>
                            </a>
                            <a
                                href="https://github.com/servesh04/MentorMap"
                                target="_blank"
                                rel="noopener noreferrer"
                                className="flex items-center gap-3 px-4 py-3 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700/50 hover:bg-slate-100 dark:hover:bg-slate-700/80 hover:border-slate-300 dark:hover:border-slate-600 transition-all text-foreground text-sm"
                            >
                                <Github size={18} className="text-slate-500 dark:text-slate-400" />
                                <span>GitHub Repository</span>
                            </a>
                        </div>
                    </section>

                    {/* ── Section 4: App Info ── */}
                    <div className="text-center pt-4 pb-2 border-t border-slate-200 dark:border-slate-700/30">
                        <p className="text-xs text-slate-500">MentorMap v{APP_VERSION}</p>
                        <p className="text-[10px] text-slate-600 mt-1">Made with ❤️ for learners everywhere</p>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default HelpSupportModal;
